os: osx
osx_image: xcode11.2
language: swift
rvm: 2.6.1

addons:
  homebrew:
    brewfile: true
    update: true

cache:
  bundler: true
  cocoapods: true
  directories:
    - $HOME/.rvm/


branches:
  only:
    - master
    - development
    - /^hotfix.*$/
    - /^feature.*$/
    - /^release.*$/

env:
   global:
     - PROJECT="{PROJECT}.xcodeproj"
     # Add your code climate reporter ID:
     - CC_TEST_REPORTER_ID="FIX_ME"
     # Add your danger API token:
     - DANGER_GITHUB_API_TOKEN="FIX_ME"
     - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

before_install:
  - make setup
  - chmod a+x ./fastlane/scripts/*.sh

jobs:
  include:
    - &test
      stage: test
      name: iOS test (iPhone Pro)
      env:
        - LANE="test_iphone_pro"
      before_script:
        - bundle exec danger
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64> ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - "./cc-test-reporter before-build"
      script:
        - bundle exec fastlane "$LANE"
      after_success:
        - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"

    - <<: *test
      name: tvOS 12.1
      env:
        - LANE="test_tvOS"
      if: "(commit_message =~ /(@test tvOS)/)"

    - <<: *test
      name: macOS 12.1
      env:
        - LANE="test_macOS"
      if: "(commit_message =~ /(@test macOS)/)"

    - stage: lint
      name: pod lint
      if: branch IN (master, develop) AND (type != pull_request)
      script: bundle exec pod lib lint

    - stage: carthage
      name: Carthage build
      if: "(commit_message =~ /(@deploy carthage)/)"
      script:
        - carthage build --no-skip-current --configuration Release

stages:
  - test
  - lint
  - carthage
